<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.36">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Yuliia Heleveria and Camilo Granada Cossio">
<meta name="dcterms.date" content="2026-05-01">

<title>Armadillo Count Regression Analysis</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="vignette_files/libs/clipboard/clipboard.min.js"></script>
<script src="vignette_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="vignette_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="vignette_files/libs/quarto-html/popper.min.js"></script>
<script src="vignette_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="vignette_files/libs/quarto-html/anchor.min.js"></script>
<link href="vignette_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="vignette_files/libs/quarto-html/quarto-syntax-highlighting-845c23b38eaddc0f92fda52bfe77a8c8.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="vignette_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="vignette_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="vignette_files/libs/bootstrap/bootstrap-8ffd5f67044e5306d9846f29df41dda5.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#background" id="toc-background" class="nav-link active" data-scroll-target="#background">Background</a></li>
  <li><a href="#data-preview" id="toc-data-preview" class="nav-link" data-scroll-target="#data-preview">Data Preview</a></li>
  <li><a href="#data-summary" id="toc-data-summary" class="nav-link" data-scroll-target="#data-summary">Data Summary</a></li>
  <li><a href="#pairwise-plots" id="toc-pairwise-plots" class="nav-link" data-scroll-target="#pairwise-plots">Pairwise Plots</a></li>
  <li><a href="#model-selection-and-diagnostics" id="toc-model-selection-and-diagnostics" class="nav-link" data-scroll-target="#model-selection-and-diagnostics">Model Selection and Diagnostics</a>
  <ul class="collapse">
  <li><a href="#poisson-model-diagnostics" id="toc-poisson-model-diagnostics" class="nav-link" data-scroll-target="#poisson-model-diagnostics">Poisson Model Diagnostics</a></li>
  <li><a href="#poisson-assumption-checks" id="toc-poisson-assumption-checks" class="nav-link" data-scroll-target="#poisson-assumption-checks">Poisson Assumption Checks</a></li>
  <li><a href="#goodness-of-fit-and-influence" id="toc-goodness-of-fit-and-influence" class="nav-link" data-scroll-target="#goodness-of-fit-and-influence">Goodness of Fit and Influence</a></li>
  </ul></li>
  <li><a href="#negative-binomial-model" id="toc-negative-binomial-model" class="nav-link" data-scroll-target="#negative-binomial-model">Negative Binomial Model</a></li>
  <li><a href="#interpretation" id="toc-interpretation" class="nav-link" data-scroll-target="#interpretation">Interpretation</a>
  <ul class="collapse">
  <li><a href="#incidence-rate-ratios" id="toc-incidence-rate-ratios" class="nav-link" data-scroll-target="#incidence-rate-ratios">Incidence Rate Ratios</a></li>
  </ul></li>
  <li><a href="#interaction-analysis" id="toc-interaction-analysis" class="nav-link" data-scroll-target="#interaction-analysis">Interaction Analysis</a>
  <ul class="collapse">
  <li><a href="#simple-slopes-visualization" id="toc-simple-slopes-visualization" class="nav-link" data-scroll-target="#simple-slopes-visualization">Simple Slopes Visualization</a></li>
  <li><a href="#estimated-marginal-means" id="toc-estimated-marginal-means" class="nav-link" data-scroll-target="#estimated-marginal-means">Estimated Marginal Means</a></li>
  <li><a href="#contrasts-of-marginal-means" id="toc-contrasts-of-marginal-means" class="nav-link" data-scroll-target="#contrasts-of-marginal-means">Contrasts of Marginal Means</a></li>
  <li><a href="#marginal-effects-emtrends" id="toc-marginal-effects-emtrends" class="nav-link" data-scroll-target="#marginal-effects-emtrends">Marginal Effects (emtrends)</a></li>
  <li><a href="#contrasts-of-marginal-effects" id="toc-contrasts-of-marginal-effects" class="nav-link" data-scroll-target="#contrasts-of-marginal-effects">Contrasts of Marginal Effects</a></li>
  <li><a href="#johnson-neyman-plot" id="toc-johnson-neyman-plot" class="nav-link" data-scroll-target="#johnson-neyman-plot">Johnson-Neyman Plot</a></li>
  </ul></li>
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary">Summary</a></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Armadillo Count Regression Analysis</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Yuliia Heleveria and Camilo Granada Cossio </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">May 1, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="background" class="level2">
<h2 class="anchored" data-anchor-id="background">Background</h2>
<p>This analysis examines data collected from <span class="math inline">\(n = 38\)</span> hunters to assess whether a hunter’s age and number of treks predict the number of armadillos hunted, and whether an interaction between the two predictors is needed.</p>
<p>The proposed model is:</p>
<p><span class="math display">\[\text{Armadillos} \sim \text{Age} + \text{Treks} + \text{Age} \times \text{Treks}\]</span></p>
<p>Because the outcome is a count variable, count regression models (Poisson and Negative Binomial) are used from the Count Regression Dashboard.</p>
<hr>
</section>
<section id="data-preview" class="level2">
<h2 class="anchored" data-anchor-id="data-preview">Data Preview</h2>
<p>The dataset (<code>McMillanAcheArmadillo.csv</code>) contains four variables: <strong>Hunter</strong> (ID), <strong>Age</strong>, <strong>Armadillos</strong> (count), and <strong>Treks</strong>. A sample of the first rows is shown below.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="dat_preview.png" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption>Data preview from the Count Regression Toolkit</figcaption>
</figure>
</div>
<hr>
</section>
<section id="data-summary" class="level2">
<h2 class="anchored" data-anchor-id="data-summary">Data Summary</h2>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="dat_summary.png" class="img-fluid figure-img" style="width:85.0%"></p>
<figcaption>Count distribution and summary statistics</figcaption>
</figure>
</div>
<p>Inspection of the data reveals the following:</p>
<ul>
<li><strong>Mean:</strong> 12.08</li>
<li><strong>Variance:</strong> 189.43</li>
<li><strong>Min:</strong> 0, <strong>Max:</strong> 45</li>
<li><strong>Proportion of zeros:</strong> 0.158</li>
</ul>
<p>The variance (189.43) is substantially larger than the mean (12.08), with a mean-variance ratio of approximately <strong>15.7</strong> — a strong early indicator of overdispersion. The proportion of zero counts (15.8%) is also non-trivial.</p>
<hr>
</section>
<section id="pairwise-plots" class="level2">
<h2 class="anchored" data-anchor-id="pairwise-plots">Pairwise Plots</h2>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="pairwise_plots.png" class="img-fluid figure-img" style="width:85.0%"></p>
<figcaption>Pairwise relationships between Armadillos, Age, and Treks</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="corr_matrix.png" class="img-fluid figure-img" style="width:100.0%"></p>
<figcaption>Correlation matrix between Armadillos, Age, and Treks</figcaption>
</figure>
</div>
<p>The pairwise plots reveal positive correlations between all three variables. Notably:</p>
<ul>
<li><strong>Armadillos ~ Age:</strong> Correlation = 0.639 (***) — older hunters tend to encounter more armadillos.</li>
<li><strong>Armadillos ~ Treks:</strong> Correlation = 0.828 (***) — hunters who go on more treks encounter substantially more armadillos.</li>
<li><strong>Age ~ Treks:</strong> Correlation = 0.641 (***) — age and treks are themselves correlated, which will be relevant for multicollinearity assessment.</li>
</ul>
<hr>
</section>
<section id="model-selection-and-diagnostics" class="level2">
<h2 class="anchored" data-anchor-id="model-selection-and-diagnostics">Model Selection and Diagnostics</h2>
<section id="poisson-model-diagnostics" class="level3">
<h3 class="anchored" data-anchor-id="poisson-model-diagnostics">Poisson Model Diagnostics</h3>
<p>The initial Poisson model was fit and evaluated using the Diagnostics tab.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="pois_eval1.png" class="img-fluid figure-img" style="width:90.0%"></p>
<figcaption>Poisson model diagnostics</figcaption>
</figure>
</div>
<p>The Poisson diagnostics flagged several problems:</p>
<ul>
<li><strong>Normality of RQRs:</strong> Shapiro-Wilk p = 0.245 — RQRs appear normally distributed</li>
<li><strong>Dispersion:</strong> Overdispersion detected (ratio = <strong>3.765</strong>)</li>
<li><strong>Excess Zeros:</strong> Excess zeros detected (observed = 0.158, expected = 0.081)</li>
<li><strong>Mean-Variance Relation:</strong> Spearman |r| = 0.285 — adequate</li>
<li><strong>Model Recommendation:</strong> <em>Consider Zero-Inflated Negative Binomial (ZINB): excess zeros and overdispersion detected.</em></li>
</ul>
</section>
<section id="poisson-assumption-checks" class="level3">
<h3 class="anchored" data-anchor-id="poisson-assumption-checks">Poisson Assumption Checks</h3>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="pois_eval2.png" class="img-fluid figure-img" style="width:90.0%"></p>
<figcaption>Poisson assumption checks and influence diagnostics</figcaption>
</figure>
</div>
<p>The full Poisson assumption checks confirm:</p>
<ol type="1">
<li>Response variable contains non-negative integer counts.</li>
<li><strong>Equidispersion violated</strong> — variance (189.43) far exceeds mean (12.08), ratio = 15.68.</li>
<li><strong>Overdispersion confirmed</strong> — deviance/df = 4.24. Consider Quasi-Poisson or Negative Binomial.</li>
<li><strong>Excess zeros</strong> — observed 15.8%, expected under Poisson: 0%. Consider ZIP or ZINB.</li>
<li><strong>Possible non-linearity</strong> in log(λ) — LOESS deviation = 0.604.</li>
<li><strong>High multicollinearity</strong> — max VIF = 32.98 (driven by the interaction term).</li>
<li>Adequate events per predictor (EPP = 153).</li>
</ol>
</section>
<section id="goodness-of-fit-and-influence" class="level3">
<h3 class="anchored" data-anchor-id="goodness-of-fit-and-influence">Goodness of Fit and Influence</h3>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="pois_eval3.png" class="img-fluid figure-img" style="width:90.0%"></p>
<figcaption>Goodness of fit and zero-inflation test</figcaption>
</figure>
</div>
<ul>
<li><strong>Goodness of fit:</strong> Poor model fit (Pearson χ² = 128.02, df = 34, p = 0) — the Poisson model is misspecified.</li>
<li><strong>Influence checks:</strong> Few/no observations with large leverage, Cook’s distance, or DFFITS values</li>
<li><strong>Zero-inflation test (DHARMa):</strong> p = 0.032 — borderline evidence of excess zeros.</li>
</ul>
<hr>
</section>
</section>
<section id="negative-binomial-model" class="level2">
<h2 class="anchored" data-anchor-id="negative-binomial-model">Negative Binomial Model</h2>
<p>Given the overdispersion detected under Poisson, a <strong>Negative Binomial</strong> model was fit instead.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="nb_eval.png" class="img-fluid figure-img" style="width:90.0%"></p>
<figcaption>Negative Binomial model diagnostics</figcaption>
</figure>
</div>
<p>The Negative Binomial diagnostics show substantial improvement across all checks:</p>
<ul>
<li><strong>Normality of RQRs:</strong> Shapiro-Wilk p = 0.099 — RQRs appear normally distributed</li>
<li><strong>Dispersion:</strong> Ratio = <strong>0.867</strong> — dispersion looks adequate</li>
<li><strong>Excess Zeros:</strong> Observed = 0.158, expected = 0.147 — zero proportion looks adequate</li>
<li><strong>Mean-Variance Relation:</strong> Spearman |r| = 0.024 — adequate</li>
<li><strong>Model Recommendation:</strong> <em>Current model (Negative Binomial) appears adequately specified.</em></li>
</ul>
<hr>
</section>
<section id="interpretation" class="level2">
<h2 class="anchored" data-anchor-id="interpretation">Interpretation</h2>
<section id="incidence-rate-ratios" class="level3">
<h3 class="anchored" data-anchor-id="incidence-rate-ratios">Incidence Rate Ratios</h3>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="coef_interpret.png" class="img-fluid figure-img" style="width:90.0%"></p>
<figcaption>Model interpretation — Negative Binomial IRR table</figcaption>
</figure>
</div>
<p>The Negative Binomial model results yield the following <strong>Incidence Rate Ratios (IRRs)</strong>:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Term</th>
<th>Estimate</th>
<th>IRR</th>
<th>% Change</th>
<th>p-value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>(Intercept)</td>
<td>-2.60</td>
<td>0.07</td>
<td>-92.54%</td>
<td>&lt; 0.001</td>
</tr>
<tr class="even">
<td>Age</td>
<td>0.09</td>
<td>1.10</td>
<td>+9.54%</td>
<td>&lt; 0.001</td>
</tr>
<tr class="odd">
<td>Treks</td>
<td>0.10</td>
<td>1.10</td>
<td>+10.40%</td>
<td>&lt; 0.001</td>
</tr>
<tr class="even">
<td>Age:Treks</td>
<td>-0.00</td>
<td>1.00</td>
<td>-0.16%</td>
<td>&lt; 0.001</td>
</tr>
</tbody>
</table>
<p><strong>Interpretation of each term:</strong></p>
<ul>
<li><p><strong>Age:</strong> For every one-unit increase in age, the expected count of armadillos is multiplied by 1.10 — a 9.54% increase — holding treks constant (95% CI: 1.06, 1.13; p &lt; 0.001).</p></li>
<li><p><strong>Treks:</strong> For every one-unit increase in treks, the expected count of armadillos is multiplied by 1.10 — a 10.4% increase — holding age constant (95% CI: 1.07, 1.14; p &lt; 0.001).</p></li>
<li><p><strong>Age × Treks interaction:</strong> The multiplicative effect of treks on armadillo count decreases by 0.16% for each additional year of age (IRR = 0.9984; 95% CI: 0.9978, 0.9991; p &lt; 0.001). Although small in magnitude, this interaction is statistically significant — the effect of treks depends on the hunter’s age.</p></li>
</ul>
<hr>
</section>
</section>
<section id="interaction-analysis" class="level2">
<h2 class="anchored" data-anchor-id="interaction-analysis">Interaction Analysis</h2>
<p>To further understand the significant Age × Treks interaction, the interaction was examined using simple slopes, estimated marginal means, marginal effects (emtrends), and a Johnson-Neyman plot. The moderator variable is Age and the focal predictor is Treks.</p>
<section id="simple-slopes-visualization" class="level3">
<h3 class="anchored" data-anchor-id="simple-slopes-visualization">Simple Slopes Visualization</h3>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="slope.png" class="img-fluid figure-img" style="width:85.0%"></p>
<figcaption>Simple slopes plot — predicted armadillo count by Treks at low and high Age</figcaption>
</figure>
</div>
<p>The simple slopes plot shows predicted armadillo counts as a function of Treks, separately for hunters with low age (Mean − 1SD = 22.23) and high age (Mean + 1SD = 51.89). The slope for low-age hunters is substantially steeper than for high-age hunters, indicating that the positive effect of treks on armadillo encounters is stronger among younger hunters. Both lines increase with treks, but the low-age group shows considerably more uncertainty at higher trek values.</p>
<hr>
</section>
<section id="estimated-marginal-means" class="level3">
<h3 class="anchored" data-anchor-id="estimated-marginal-means">Estimated Marginal Means</h3>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="emm.png" class="img-fluid figure-img" style="width:90.0%"></p>
<figcaption>Estimated marginal means and contrasts of marginal means</figcaption>
</figure>
</div>
<p>The estimated marginal means of Armadillos at the four combinations of Age (±1SD) and Treks (±1SD) are:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 8%">
<col style="width: 12%">
<col style="width: 33%">
<col style="width: 8%">
<col style="width: 17%">
<col style="width: 17%">
</colgroup>
<thead>
<tr class="header">
<th>Age</th>
<th>Treks</th>
<th>Est. Marginal Mean</th>
<th>SE</th>
<th>Lower CI</th>
<th>Upper CI</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Low (Mean − 1SD = 3.76)</td>
<td>Low (Mean − 1SD = 22.23)</td>
<td>0.72</td>
<td>0.22</td>
<td>0.39</td>
<td>1.32</td>
</tr>
<tr class="even">
<td>High (Mean + 1SD = 64.77)</td>
<td>Low (Mean − 1SD = 22.23)</td>
<td>35.85</td>
<td>15.22</td>
<td>15.60</td>
<td>82.41</td>
</tr>
<tr class="odd">
<td>Low (Mean − 1SD = 3.76)</td>
<td>High (Mean + 1SD = 51.89)</td>
<td>9.01</td>
<td>2.48</td>
<td>5.25</td>
<td>15.46</td>
</tr>
<tr class="even">
<td>High (Mean + 1SD = 64.77)</td>
<td>High (Mean + 1SD = 51.89)</td>
<td>26.37</td>
<td>3.78</td>
<td>19.92</td>
<td>34.92</td>
</tr>
</tbody>
</table>
<p><strong>Interpretation:</strong></p>
<ul>
<li>When Age is low (3.76) and Treks is low (22.23), the estimated marginal mean of Armadillos is 0.72 (95% CI: 0.39, 1.32).</li>
<li>When Age is high (64.77) and Treks is low (22.23), the estimated marginal mean is 35.85 (95% CI: 15.60, 82.41) — a large increase driven by age alone at low trek frequency.</li>
<li>When Age is low (3.76) and Treks is high (51.89), the estimated marginal mean is 9.01 (95% CI: 5.25, 15.46).</li>
<li>When Age is high (64.77) and Treks is high (51.89), the estimated marginal mean is 26.37 (95% CI: 19.92, 34.92).</li>
</ul>
<hr>
</section>
<section id="contrasts-of-marginal-means" class="level3">
<h3 class="anchored" data-anchor-id="contrasts-of-marginal-means">Contrasts of Marginal Means</h3>
<p>All pairwise contrasts between the four Age × Treks combinations were statistically significant except the comparison between High Age/Low Treks and High Age/High Treks (t = 0.74, p = 0.88), suggesting that at high ages, the number of treks has little additional impact on predicted armadillo counts.</p>
<p>Notable contrasts:</p>
<ul>
<li><strong>Treks3.76 Age22.23 / Treks64.77 Age22.23:</strong> t = −6.51, p &lt; 0.0001 (95% CI: 0.00, 0.09) — significant.</li>
<li><strong>Treks3.76 Age22.23 / Treks3.76 Age51.89:</strong> t = −6.04, p &lt; 0.0001 (95% CI: 0.03, 0.23) — significant.</li>
<li><strong>Treks64.77 Age22.23 / Treks3.76 Age51.89:</strong> t = 2.57, p = 0.0499 (95% CI: 1.00, 15.82) — marginally significant.</li>
<li><strong>Treks3.76 Age51.89 / Treks64.77 Age51.89:</strong> t = −4.03, p = 0.0003 (95% CI: 0.17, 0.68) — significant.</li>
</ul>
<hr>
</section>
<section id="marginal-effects-emtrends" class="level3">
<h3 class="anchored" data-anchor-id="marginal-effects-emtrends">Marginal Effects (emtrends)</h3>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="emtrends.png" class="img-fluid figure-img" style="width:90.0%"></p>
<figcaption>Marginal effects and contrasts of marginal effects</figcaption>
</figure>
</div>
<p>The marginal effects (slopes of Treks) at low and high levels of Age are:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Age</th>
<th>Slope of Treks</th>
<th>SE</th>
<th>t ratio</th>
<th>p-value</th>
<th>Lower CI</th>
<th>Upper CI</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Low (Mean − 1SD)</td>
<td>0.06</td>
<td>0.01</td>
<td>6.51</td>
<td>&lt; 0.0001</td>
<td>0.04</td>
<td>0.08</td>
</tr>
<tr class="even">
<td>High (Mean + 1SD)</td>
<td>0.02</td>
<td>0.00</td>
<td>4.03</td>
<td>0.0001</td>
<td>0.01</td>
<td>0.03</td>
</tr>
</tbody>
</table>
<ul>
<li>The effect of Treks is significant when Age is low (Mean − 1SD): Slope = 0.0641, t = 6.51, p &lt; 0.0001.</li>
<li>The effect of Treks is significant when Age is high (Mean + 1SD): Slope = 0.0176, t = 4.03, p = 0.0001.</li>
</ul>
<p>Although the effect of Treks is significant at both levels of Age, it is meaningfully stronger for younger hunters — the slope at low age is approximately 3.6 times larger than at high age.</p>
<hr>
</section>
<section id="contrasts-of-marginal-effects" class="level3">
<h3 class="anchored" data-anchor-id="contrasts-of-marginal-effects">Contrasts of Marginal Effects</h3>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="emtrends_cont.png" class="img-fluid figure-img" style="width:70.0%"></p>
<figcaption>Contrasts of marginal effects</figcaption>
</figure>
</div>
<p>The contrast between the two slopes confirms that the effect of Treks differs significantly by Age:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Contrast</th>
<th>Estimate</th>
<th>SE</th>
<th>t ratio</th>
<th>p-value</th>
<th>Lower CI</th>
<th>Upper CI</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Age22.23 − Age51.89</td>
<td>0.05</td>
<td>0.01</td>
<td>4.75</td>
<td>&lt; 0.0001</td>
<td>0.03</td>
<td>0.07</td>
</tr>
</tbody>
</table>
<p>The effect of Treks is significantly different between low and high Age groups (Estimate = 0.0465, t = 4.75, p &lt; 0.0001), confirming that the interaction is meaningful: younger hunters show a substantially stronger positive relationship between treks and armadillo encounters than older hunters.</p>
<hr>
</section>
<section id="johnson-neyman-plot" class="level3">
<h3 class="anchored" data-anchor-id="johnson-neyman-plot">Johnson-Neyman Plot</h3>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="jn.png" class="img-fluid figure-img" style="width:85.0%"></p>
<figcaption>Johnson-Neyman plot for the Age × Treks interaction</figcaption>
</figure>
</div>
<p>The Johnson-Neyman plot displays the slope of Treks as a continuous function of Age, with shading indicating regions of statistical significance (blue = significant, red = insignificant).</p>
<p><strong>Interpretation:</strong></p>
<ul>
<li>When Age is outside the interval [56.92], the effect of Treks is p &lt; .05.</li>
<li>The range of observed Age values is [16.5, 65.8].</li>
</ul>
<p>This means the positive effect of Treks on armadillo counts is statistically significant for most of the observed age range, but becomes non-significant at the upper tail — roughly for hunters older than 56.92 years. Younger hunters show a reliably stronger relationship between trek frequency and armadillo encounters.</p>
<hr>
</section>
</section>
<section id="summary" class="level2">
<h2 class="anchored" data-anchor-id="summary">Summary</h2>
<p>Trek frequency and age are both statistically significant predictors of armadillo encounters, and they interact. A Negative Binomial regression model was necessary to account for the overdispersion detected under the initial Poisson model (dispersion ratio = 3.77 under Poisson, 0.87 under Negative Binomial). Once the Negative Binomial model was adopted, all major diagnostic checks passed. Researchers studying armadillo encounter rates should account for both how often hunters go out and their age, as these factors jointly predict wildlife encounters.</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>